<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'login',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:57',
                'parent_id' => 45,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'logout',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'register',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'password.request',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'password.email',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'password.reset',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'password.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'home',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 0,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'role.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'role.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'role.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'role.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'role.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'role.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'role.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'permission.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'permission.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'permission.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'permission.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'permission.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'permission.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'permission.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'permission.add',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'permission.addmenu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'user.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 25,
                'icon' => NULL,
                'isURL' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'user.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 26,
                'icon' => NULL,
                'isURL' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'user.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 27,
                'icon' => NULL,
                'isURL' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'user.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 28,
                'icon' => NULL,
                'isURL' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'user.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 29,
                'icon' => NULL,
                'isURL' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'user.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 30,
                'icon' => NULL,
                'isURL' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'user.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 31,
                'icon' => NULL,
                'isURL' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'assignrole.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 32,
                'icon' => NULL,
                'isURL' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'assignrole.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 33,
                'icon' => NULL,
                'isURL' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'assignrole.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 34,
                'icon' => NULL,
                'isURL' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'assignrole.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 35,
                'icon' => NULL,
                'isURL' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'assignrole.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 36,
                'icon' => NULL,
                'isURL' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'assignrole.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 37,
                'icon' => NULL,
                'isURL' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'assignrole.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 38,
                'icon' => NULL,
                'isURL' => 1,
            ),
            38 => 
            array (
                'id' => 45,
                'name' => '#always',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:14:01',
                'updated_at' => '2019-01-02 06:16:57',
                'parent_id' => 0,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 0,
            ),
            39 => 
            array (
                'id' => 46,
                'name' => '#usermanagement',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 09:25:56',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 8,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 0,
            ),
            40 => 
            array (
                'id' => 47,
                'name' => 'menu-index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            41 => 
            array (
                'id' => 48,
                'name' => 'menu-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            42 => 
            array (
                'id' => 49,
                'name' => 'menu-build-menu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            43 => 
            array (
                'id' => 50,
                'name' => 'menu-delete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            44 => 
            array (
                'id' => 51,
                'name' => 'menu-search',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            45 => 
            array (
                'id' => 52,
                'name' => 'display-name-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
        ));
        
        
    }
}